stages:
- name: p
  steps:
  - applyAppConfig:
      catalogTemplate: p-862cd:pcatalog-mysql
      version: 0.3.8
      name: pmysql
      targetNamespace: pmysql
      answers:
        persistence.enabled: "false"
- name: c
  steps:
  - applyAppConfig:
      catalogTemplate: c-7n4rc:ccatalog-mysql
      version: 0.3.8
      name: cmysql
      targetNamespace: cmysql
      answers:
        persistence.enabled: "false"
- name: g
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mysql
      version: 0.3.8
      name: gmysql
      targetNamespace: gmysql
      answers:
        persistence.enabled: "false"
timeout: 60
notification: {}
