stages:
- name: deploy
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:library-mysql
      version: 0.3.8
      name: testm
      targetNamespace: default
timeout: 60
notification: {}
