stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: lawr/test:${CICD_EXECUTION_SEQUENCE}
    env:
      DOCKER_HOST: tcp://dind:2379
      PLUGIN_DAEMON_OFF: "true"
      PLUGIN_DEBUG: "true"
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
