stages:
- name: Build Backend
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo $FOO
    env:
      FOO: ${CICD_GIT_COMMIT}
    when:
      branch: {}
      event: {}
notification: {}
