stages:
- name: Build Backend
  steps:
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :api:shadowJar
    when:
      branch:
        include:
        - api*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :collector:shadowJar
    when:
      branch:
        include:
        - collector*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :consumer:shadowJar
    when:
      branch:
        include:
        - consumer*
      event:
        include:
        - tag
  - runScriptConfig:
      image: frekele/gradle
      shellScript: gradle :sync:shadowJar
    when:
      branch:
        include:
        - sync*
      event:
        include:
        - tag
- name: Publish to QA
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/qa/Dockerfile
      buildContext: .
      tag: kodelabs-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - QA
        - api*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/qa/Dockerfile
      buildContext: .
      tag: kodelabs-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - QA
        - collector*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/qa/Dockerfile
      buildContext: .
      tag: kodelabs-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - QA
        - consumer*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/qa/Dockerfile
      buildContext: .
      tag: kodelabs-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - QA
        - sync*
      event:
        include:
        - tag
- name: Publish to Staging
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Staging
        - api*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Staging
        - collector*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Staging
        - consumer*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/stagign/Dockerfile
      buildContext: .
      tag: kodelabs-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Staging
        - sync*
      event:
        include:
        - tag
- name: Publish to Production
  steps:
  - publishImageConfig:
      dockerfilePath: ./k8s/api/prod/Dockerfile
      buildContext: .
      tag: kodelabs-api:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Production
        - api*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/collector/prod/Dockerfile
      buildContext: .
      tag: kodelabs-collector:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Production
        - collector*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/consumer/prod/Dockerfile
      buildContext: .
      tag: kodelabs-consumer:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Production
        - consumer*
      event:
        include:
        - tag
  - publishImageConfig:
      dockerfilePath: ./k8s/sync/prod/Dockerfile
      buildContext: .
      tag: kodelabs-sync:${CICD_GIT_COMMIT}.${CICD_GIT_BRANCH}.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: hub.kodelabs.tk
    when:
      branch:
        include:
        - Production
        - sync*
      event:
        include:
        - tag
- name: Deploy to QA
  steps:
  - applyYamlConfig:
      path: k8s/api/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - QA
        - api*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/collector/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - QA
        - collector*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/consumer/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - QA
        - consumer*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/sync/qa/deployment-qa.yaml
    when:
      branch:
        include:
        - QA
        - sync*
      event:
        include:
        - tag
- name: Deploy to Staging
  steps:
  - applyYamlConfig:
      path: k8s/api/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - Staging
        - api*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/collector/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - Staging
        - collector*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/consumer/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - Staging
        - consumer*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/sync/stagign/deployment-staging.yaml
    when:
      branch:
        include:
        - Staging
        - sync*
      event:
        include:
        - tag
- name: Deploy to Production
  steps:
  - applyYamlConfig:
      path: k8s/api/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - Production
        - api*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/collector/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - Production
        - collector*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/consumer/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - Production
        - consumer*
      event:
        include:
        - tag
  - applyYamlConfig:
      path: k8s/sync/prod/deployment-prod.yaml
    when:
      branch:
        include:
        - Production
        - sync*
      event:
        include:
        - tag