stages:
- name: custom-publish
  steps:
  - runScriptConfig:
      image: plugins/docker:17.12
      shellScript: ls
    env:
      PLUGIN_CONTEXT: .
      PLUGIN_DOCKERFILE: ./Dockerfile
      PLUGIN_REPO: lawr/test
timeout: 60
notification: {}
