stages:
- name: Build Backend
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: ls
  - runScriptConfig:
      image: busybox
      shellScript: echo taging qa
    when:
      branch: [ "QA-*" ]
      event: tag
