stages:
- name: build
  steps:
  - runScriptConfig:
      image: busybox
      shellScript: echo 1
    cpuRequest: 10m
    cpuLimit: 100m
    memoryRequest: 10Mi
    memoryLimit: 100Mi
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example/app:v1
      registry: 127.0.0.1:34239
timeout: 60
