kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
        - name: api
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          env:
          - name: en
            value: ${TESTME}
          ports:
            - containerPort: 80
